config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  get 'search', to: "restaurants#index", as: "restaurants"

end

app/models/clothing.rb
class Clothing

	def initialize(fanciness)
		@fanciness = fanciness.to_i
		if fanciness >= 4
			@clothes = "http://pngimg.com/upload/suit_PNG8120.png"
			@title   = "Suit up! This is fancy business!"
		elsif fanciness <= 2
			@clothes = "http://images.gearjunkie.com/uploads/2015/09/stormy-kromer-flannel.png"
			@title   = "Lumber up! No one really cares, enjoy your food."
		else
			@clothes ="http://myfashionwants.com/wp-content/uploads/2013/09/7-For-All-Mankind-Womens-Colorblock-Denim-Shirt.png"
			@title   = "Why do you care? Pretty normal place man."
		end
			
	end

	attr_accessor :fanciness,:clothes,:title
end

app/models/restaurant.rb
class Restaurant

	def self.search(q)
		conn = Faraday.new(:url => 'https://developers.zomato.com') do |faraday|
		  faraday.request  :url_encoded             # form-encode POST params
		  faraday.response :logger                  # log requests to STDOUT
		  faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
		end

		response = conn.get "/api/v2.1/search?q=#{URI.escape(q)}" do |req|    # GET http://sushi.com/nigiri/sake.json
			req.headers['Content-Type'] = 'application/json'
			req.headers['user_key'] = 'd4b925d03141f6f9fbff52d0e57a49c7'
		end		
		Restaurant.parse(response.body)
	end

	def self.parse(response)
		begin
			unparsed_restaurants = JSON.parse(response.to_s)
		rescue Exception => e
			return []
		end		
		return [] if unparsed_restaurants["restaurants"].nil?
		parsed_restaurants = []
		unparsed_restaurants["restaurants"].each do |unparsed_restaurant|
			unparsed_restaurant = unparsed_restaurant["restaurant"]
			restaurant = Restaurant.new(unparsed_restaurant)
			parsed_restaurants << restaurant
		end
		parsed_restaurants
	end

	def initialize(unparsed_restaurant)
		@id = unparsed_restaurant["id"]
		@name = unparsed_restaurant["name"]
		@url = unparsed_restaurant["url"]
		@city = unparsed_restaurant["location"]["city"]
		@thumb = unparsed_restaurant["thumb"]
		@rating = unparsed_restaurant["user_rating"]["aggregate_rating"]
		@avg_cost_for_two = unparsed_restaurant["average_cost_for_two"]
		@price_range = unparsed_restaurant["price_range"]
		@clothing = Clothing.new(@price_range)
	end

	attr_accessor :id,:name,:url,:city,:thumb,:rating,:avg_cost_for_two,:price_range,:clothing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	
	def index
		if params[:q].present?
			@restaurants = Restaurant.search(params[:q])
		end

		respond_to do |format|
			format.html
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_nav.html.erb
<div class="bs-component">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <h3>
            <%= link_to root_path, style: "" do %>
              <%= image_tag "logo.png", style: "width:100px;" %>
            <% end %>
            What Should I Wear?
          </h3>
      </div>
    </div>
  </nav>
  <div id="source-button" class="btn btn-primary btn-xs" style="display: none;">&lt; &gt;</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whatshouldiwear</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_jumbotron.html.erb
<div class="bs-component text-center">  
	<div class="jumbotron" style="background-image: url(http://images.hackett.com/media/wysiwyg/aw15_suits_banner_1.jpg)">
    	<h1>Don't know what to wear?</h1>
    	<p>We help you getting your clothing right for your date on that <del>cheap</del> fancy restaurant .</p>
    	<div class="col-md-9 col-md-offset-3">
	    	<%= form_tag restaurants_path, method: :get, class: "navbar-form navbar-left", role: "search", style: "width:66%;" do %>
	          <div class="form-group" style="width:100%">
	            <input type="text" name="q" class="form-control" placeholder="Search for restaurants" style="width:100%" value="<%= params[:q] %>">
	          </div>
	          <p>
	    		<button class="btn btn-primary btn-lg" data-disable-with="Searching..." style="margin-top:20px;">Find restaurants</button>
	    	  </p>
	        <% end %>
	    </div>    	    	
  	</div>
	<div id="source-button" class="btn btn-primary btn-xs" style="display: none;">&lt; &gt;</div>
</div>

app/views/restaurants/_restaurant.html.erb
<tr data-toggle="modal" data-target="#restaurant-<%= restaurant.id %>">
	<td><%= image_tag restaurant.thumb %></td>
	<td style="vertical-align:middle;"><strong><%= restaurant.name %></strong></td>
	<td style="vertical-align:middle;"><%= restaurant.city %></td>
	<td style="vertical-align:middle;"><%= restaurant.rating %></td>
	<td style="vertical-align:middle;">
		<% restaurant.price_range.to_i.times do %>
			<%= image_tag "logo.png", style: "width:20px;" %>
		<% end %>
	</td>
</tr>

<!-- Modal -->
<div class="modal fade" id="restaurant-<%= restaurant.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
        	<% restaurant.price_range.to_i.times do %>
	      		<%= image_tag "logo.png", style: "width:60px;" %>
	      	<% end %>
        </h4>
      </div>
      <div class="modal-body">
        <h2><%= restaurant.clothing.title %></h2>
        <%= image_tag restaurant.clothing.clothes, style: "width:200px;" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Great!</button>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/_results.html.erb
<div class="bs-component">
	<div class="col-lg-offset-2 col-lg-8 text-center" style="color:black">
	<% if restaurants.empty? %>
		<h2>No results found </h2>
	<% else %>
		<h2>Found <%= restaurants.count %> restaurants </h2>
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th></th>
					<th class="text-center">Name</th>
					<th class="text-center">City</th>
					<th class="text-center">Rating</th>
					<th class="text-center">Fanciness</th>
				</tr>
			</thead>
			<tbody>
				<% restaurants.each do |restaurant| %>
					<%= render 'restaurant', restaurant:restaurant %>
				<% end %>
			</tbody>
		</table
	<% end %>
	</div>
</div>

app/views/restaurants/index.html.erb
<%= render 'layouts/nav' %>
<%= render 'jumbotron' %>
<%= render 'results', restaurants: @restaurants if params[:q].present? %>